export default {
  'courses.introduction': 'Hier sind die Kurse, die ich in der Universität nahm.',

  'semester.comment.amazon-coop': 'Praktikum bei Amazon.com',
  'semester.comment.jf-oberlin': 'Studierte an J.F. Oberlin University in Machida, Tokio, Japan',

  'courses.algorithms': 'Algorithmen',
  'courses.calculus-2': 'Infinitesimalrechnung für Wissenschaft und Ingenieurwesen 2',
  'courses.calculus-3': 'Infinitesimalrechnung für Wissenschaft und Ingenieurwesen 3',
  'courses.compilers': 'Compilers',
  'courses.computer-organization': 'Computer-Organisation',
  'courses.computers-and-society': 'Computers und Gesellschaft',
  'courses.cs-is': 'Übersicht CS/IS',
  'courses.directed-study-acl2': 'Gerichtet Studie (ACL2)',
  'courses.directed-study-dmtcp': 'Gerichtete Studie (DMTCP)',
  'courses.directed-study-dmtcp-openmpi': 'Gerichtete Studie (DMTCP/OpenMPI)',
  'courses.discrete-math': 'Diskrete Mathematik',
  'courses.freshman-seminar': 'Computer Science Seminar für Erstsemester',
  'courses.fundamentals-of-ai': 'Grundlagen von Künstlicher Intelligenz',
  'courses.fundies-1': 'Grundlagen der Informatik 1',
  'courses.gpu-programming': 'Allgemeine GPU Programmierung',
  'courses.group-theory': 'Gruppentheorie',
  'courses.intensive-operating-systems': 'Intensive Betriebssysteme',
  'courses.japanese-literature': 'Japanische Literatur und Kultur',
  'courses.linear-algebra': 'Lineare Algebra',
  'courses.masters-level': 'bezeichnet einen Master-Level-Kurs',
  'courses.mobile-application-development': 'Mobile Applikation Entwicklung',
  'courses.network-security': 'Netzwerksicherheit',
  'courses.object-oriented': 'Objektorientiertes Design',
  'courses.phd-level': 'bezeichnet einen PhD-Level-Kurs',
  'courses.philosophy': 'Einführung in die Philosophie',
  'courses.physics-1': 'Physik 1 für Ingenieuren',
  'courses.physics-2': 'Physik 2 für Ingenieuren',
  'courses.principles-of-pl': 'Grundlagen der Programmiersprachen',
  'courses.probability': 'Probabilität und Statistik',
  'courses.public-policy': 'Public Policy und Verwaltung',
  'courses.research-hpc': 'Forschung von Hochleistungsrechnen',
  'courses.software-development': 'Software-Entwicklung',
  'courses.symbolic-logic': 'Symbolische Logik',
  'courses.theory-of-computation': 'Theorie der Berechnung',
  'courses.writing-technical': 'Schreiben für die Technische Berufe',
};
